name: Publish
on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Time
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d.%H-%M-%S')" >> $GITHUB_OUTPUT
          echo "$(date +'%Y-%m-%d.%H-%M')" > ./YMCL.Main/Public/Texts/DateTime.txt
          echo "title=$(date +'%Y-%m-%d.%H-%M')" >> $GITHUB_OUTPUT
      - name: Dependency
        run: |
          dotnet tool install -g KuiperZone.PupNet
          sudo apt-get update
          sudo apt-get install fuse
      - name: Build-AppImage
        run: |
          cd ./YMCL.Main
          sudo su
          pupnet --runtime linux-x64 --kind appimage -y
          pupnet --runtime linux-arm --kind appimage -y
          pupnet --runtime linux-arm64 --kind appimage -y
      - name: Rename
        run: |
          mv ./YMCL.Main/bin/Release/net8.0/win-x86/publish/YMCL.Main.exe ./YMCL.Main/bin/Release/net8.0/win-x86/publish/YMCL.Main.win.x86.exe
          mv ./YMCL.Main/bin/Release/net8.0/win-x64/publish/YMCL.Main.exe ./YMCL.Main/bin/Release/net8.0/win-x64/publish/YMCL.Main.win.x64.exe
          mv ./YMCL.Main/bin/Release/net8.0/osx-x64/publish/YMCL.Main ./YMCL.Main/bin/Release/net8.0/osx-x64/publish/YMCL.Main.osx.x64.bin
          mv ./YMCL.Main/bin/Release/net8.0/osx-arm64/publish/YMCL.Main ./YMCL.Main/bin/Release/net8.0/osx-arm64/publish/YMCL.Main.osx.arm64.bin
          mv ./YMCL.Main/bin/Release/net8.0/linux-x64/publish/YMCL.Main ./YMCL.Main/bin/Release/net8.0/linux-x64/publish/YMCL.Main.linux.x64.bin
          mv ./YMCL.Main/bin/Release/net8.0/linux-arm/publish/YMCL.Main ./YMCL.Main/bin/Release/net8.0/linux-arm/publish/YMCL.Main.linux.arm.bin
          mv ./YMCL.Main/bin/Release/net8.0/linux-arm64/publish/YMCL.Main ./YMCL.Main/bin/Release/net8.0/linux-arm64/publish/YMCL.Main.linux.arm64.bin
      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          title: "v${{ steps.date.outputs.title }}"
          automatic_release_tag: "AutoPublish-${{ steps.date.outputs.date }}"
          prerelease: false
          files: |
            YMCL.Main/bin/Release/net8.0/osx-arm64/publish/YMCL.Main.osx.arm64.bin
            YMCL.Main/bin/Release/net8.0/osx-x64/publish/YMCL.Main.osx.x64.bin
            YMCL.Main/bin/Release/net8.0/linux-arm64/publish/YMCL.Main.linux.arm64.bin
            YMCL.Main/bin/Release/net8.0/linux-arm/publish/YMCL.Main.linux.arm.bin
            YMCL.Main/bin/Release/net8.0/linux-x64/publish/YMCL.Main.linux.x64.bin
            YMCL.Main/bin/Release/net8.0/win-x86/publish/YMCL.Main.win.x86.exe
            YMCL.Main/bin/Release/net8.0/win-x64/publish/YMCL.Main.win.x64.exe
            YMCL.Main/bin/Release/net8.0/osx-arm64/publish/YMCL.Main.alone.osx.arm64.bin
            YMCL.Main/bin/Release/net8.0/osx-x64/publish/YMCL.Main.alone.osx.x64.bin
            YMCL.Main/bin/Release/net8.0/linux-arm64/publish/YMCL.Main.alone.linux.arm64.bin
            YMCL.Main/bin/Release/net8.0/linux-arm/publish/YMCL.Main.alone.linux.arm.bin
            YMCL.Main/bin/Release/net8.0/linux-x64/publish/YMCL.Main.alone.linux.x64.bin
            YMCL.Main/bin/Release/net8.0/win-x86/publish/YMCL.Main.alone.win.x86.exe
            YMCL.Main/bin/Release/net8.0/win-x64/publish/YMCL.Main.alone.win.x64.exe
