name: Publish
on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Time
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d.%H-%M-%S')" >> $GITHUB_OUTPUT
          echo "$(date +'%Y-%m-%d.%H-%M')" > ./YMCL.Main/Public/Texts/DateTime.txt
          echo "title=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT
      - name: Dependency
        run: |
          dotnet tool install -g KuiperZone.PupNet
          sudo apt-get update
          sudo apt-get install fuse
      - name: Build-AppImage
        run: |
          cd ./YMCL.Main
          sudo su
          pupnet --runtime linux-x64 --kind appimage -o YMCL.Main.linux.x64.AppImage -y
          pupnet --runtime linux-arm --kind appimage -o YMCL.Main.linux.arm.AppImage -y
          pupnet --runtime linux-arm64 --kind appimage -o YMCL.Main.linux.arm64.AppImage -y
      - name: Build-MacOsApp
        run: |
          cd ./YMCL.Main
          sudo su
          dotnet restore -r osx-x64
          dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64  -property:Configuration=Release -p:SelfContained=true
          dotnet restore -r osx-arm64
          dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-arm64  -property:Configuration=Release -p:SelfContained=true
          cd ./bin/Release/net8.0
          zip -9 -r ./YMCL.Main.osx.mac.x64.app.zip ./osx-x64/publish/YMCL.app
          zip -9 -r ./YMCL.Main.osx.mac.arm64.app.zip ./osx-arm64/publish/YMCL.app
      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          title: "v${{ steps.date.outputs.title }}"
          automatic_release_tag: "AutoPublish-${{ steps.date.outputs.date }}"
          prerelease: false
          files: |
            YMCL.Main/Deploy/OUT/*
