name: Publish
on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Time
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d.%H-%M-%S')" >> $GITHUB_OUTPUT
          echo "$(date +'%Y-%m-%d.%H-%M')" > ./YMCL.Main/Public/Texts/DateTime.txt
          echo "title=$(date +'%Y-%m-%d.%H-%M')" >> $GITHUB_OUTPUT
      - name: Dependency
        run: |
          dotnet tool install -g KuiperZone.PupNet
          sudo apt-get update
          sudo apt-get install fuse
      - name: Build-AppImage
        run: |
          cd ./YMCL.Main
          sudo su
          pupnet --runtime linux-x64 --kind appimage -o YMCL.linux.x64.AppImage -y
          pupnet --runtime linux-arm --kind appimage -o YMCL.linux.arm.AppImage -y
          pupnet --runtime linux-arm64 --kind appimage -o YMCL.linux.arm64.AppImage -y
      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          title: "v${{ steps.date.outputs.title }}"
          automatic_release_tag: "AutoPublish-${{ steps.date.outputs.date }}"
          prerelease: false
          files: |
            YMCL.Main/Deploy/OUT/*
